# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 853)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(255, 237, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cameraLabel = QtWidgets.QLabel(self.centralwidget)
        self.cameraLabel.setGeometry(QtCore.QRect(330, 0, 611, 511))
        self.cameraLabel.setStyleSheet("QPushButton {\n"
"  border-radius: 40px;\n"
"}")
        self.cameraLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cameraLabel.setLineWidth(2)
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.fireButton = QtWidgets.QPushButton(self.centralwidget)
        self.fireButton.setGeometry(QtCore.QRect(160, 170, 111, 81))
        self.fireButton.setMinimumSize(QtCore.QSize(80, 80))
        self.fireButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.fireButton.setObjectName("fireButton")
        self.hedefyonelButton = QtWidgets.QPushButton(self.centralwidget)
        self.hedefyonelButton.setGeometry(QtCore.QRect(40, 170, 111, 81))
        self.hedefyonelButton.setMinimumSize(QtCore.QSize(80, 80))
        self.hedefyonelButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.hedefyonelButton.setObjectName("hedefyonelButton")
        self.tableWidget_results = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_results.setGeometry(QtCore.QRect(330, 520, 561, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_results.sizePolicy().hasHeightForWidth())
        self.tableWidget_results.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_results.setFont(font)
        self.tableWidget_results.setAutoFillBackground(True)
        self.tableWidget_results.setStyleSheet("")
        self.tableWidget_results.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget_results.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_results.setLineWidth(5)
        self.tableWidget_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_results.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_results.setObjectName("tableWidget_results")
        self.tableWidget_results.setColumnCount(4)
        self.tableWidget_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(3, item)
        self.tableWidget_results.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_results.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_results.horizontalHeader().setStretchLastSection(True)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 251, 241))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 550, 251, 231))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(3)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 350, 251, 131))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(3)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 330, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 237, 218);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 530, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 237, 218);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setUnderline(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 237, 218);")
        self.label_9.setObjectName("label_9")
        self.hedeftakipButton = QtWidgets.QPushButton(self.centralwidget)
        self.hedeftakipButton.setGeometry(QtCore.QRect(160, 80, 111, 81))
        self.hedeftakipButton.setMinimumSize(QtCore.QSize(80, 80))
        self.hedeftakipButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.hedeftakipButton.setObjectName("hedeftakipButton")
        self.angajmankabulButton = QtWidgets.QPushButton(self.centralwidget)
        self.angajmankabulButton.setGeometry(QtCore.QRect(60, 590, 201, 80))
        self.angajmankabulButton.setMinimumSize(QtCore.QSize(80, 80))
        self.angajmankabulButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.angajmankabulButton.setObjectName("angajmankabulButton")
        self.otonomButton = QtWidgets.QPushButton(self.centralwidget)
        self.otonomButton.setGeometry(QtCore.QRect(70, 380, 171, 81))
        self.otonomButton.setMinimumSize(QtCore.QSize(80, 80))
        self.otonomButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.otonomButton.setObjectName("otonomButton")
        self.angajmadonusButton = QtWidgets.QPushButton(self.centralwidget)
        self.angajmadonusButton.setGeometry(QtCore.QRect(60, 680, 201, 81))
        self.angajmadonusButton.setMinimumSize(QtCore.QSize(80, 80))
        self.angajmadonusButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.angajmadonusButton.setObjectName("angajmadonusButton")
        self.gorev1Button = QtWidgets.QPushButton(self.centralwidget)
        self.gorev1Button.setGeometry(QtCore.QRect(1010, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gorev1Button.setFont(font)
        self.gorev1Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;}")
        self.gorev1Button.setObjectName("gorev1Button")
        self.gorev2Button = QtWidgets.QPushButton(self.centralwidget)
        self.gorev2Button.setGeometry(QtCore.QRect(1010, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gorev2Button.setFont(font)
        self.gorev2Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;}")
        self.gorev2Button.setObjectName("gorev2Button")
        self.gorev3Button = QtWidgets.QPushButton(self.centralwidget)
        self.gorev3Button.setGeometry(QtCore.QRect(1010, 270, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gorev3Button.setFont(font)
        self.gorev3Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;}")
        self.gorev3Button.setObjectName("gorev3Button")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1000, 120, 161, 221))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(920, 540, 231, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hedeftespitButton = QtWidgets.QPushButton(self.centralwidget)
        self.hedeftespitButton.setGeometry(QtCore.QRect(40, 80, 111, 81))
        self.hedeftespitButton.setMinimumSize(QtCore.QSize(80, 80))
        self.hedeftespitButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border: 2px solid darkred;\n"
"    border-radius: 40px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: darkred;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: maroon;\n"
"}\n"
"")
        self.hedeftespitButton.setObjectName("hedeftespitButton")
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.cameraLabel.raise_()
        self.fireButton.raise_()
        self.hedefyonelButton.raise_()
        self.tableWidget_results.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.hedeftakipButton.raise_()
        self.angajmankabulButton.raise_()
        self.otonomButton.raise_()
        self.angajmadonusButton.raise_()
        self.gorev1Button.raise_()
        self.gorev2Button.raise_()
        self.gorev3Button.raise_()
        self.frame.raise_()
        self.hedeftespitButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSistem_Loglar = QtWidgets.QAction(MainWindow)
        self.actionSistem_Loglar.setObjectName("actionSistem_Loglar")
        self.menuMen.addAction(self.actionSistem_Loglar)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fireButton.setText(_translate("MainWindow", "ATEŞ ET"))
        self.hedefyonelButton.setText(_translate("MainWindow", "Hedefe Yönel"))
        item = self.tableWidget_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Class"))
        item = self.tableWidget_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Confidence"))
        item = self.tableWidget_results.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "BBox"))
        self.label_7.setText(_translate("MainWindow", "Otonom Mod"))
        self.label_8.setText(_translate("MainWindow", "Angajman Mod"))
        self.label_9.setText(_translate("MainWindow", "Manuel Mod"))
        self.hedeftakipButton.setText(_translate("MainWindow", "Hedef Takip"))
        self.angajmankabulButton.setText(_translate("MainWindow", "Angajman Kabul Başlat"))
        self.otonomButton.setText(_translate("MainWindow", "Otonom Mod"))
        self.angajmadonusButton.setText(_translate("MainWindow", "Angajmana Dönüş Başlat"))
        self.gorev1Button.setText(_translate("MainWindow", "Görev 1"))
        self.gorev2Button.setText(_translate("MainWindow", "Görev 2"))
        self.gorev3Button.setText(_translate("MainWindow", "Görev 3"))
        self.hedeftespitButton.setText(_translate("MainWindow", "Hedef Tespit"))
        self.menuMen.setTitle(_translate("MainWindow", "Menü"))
        self.actionSistem_Loglar.setText(_translate("MainWindow", "Sistem Logları"))
